export const PRELOADED_MAJORS = [
  "Computer Science",
  "Software Engineering",
  "Information Systems",
  "Data Science",
  "Cybersecurity",
  "Business Administration",
  "Accounting",
  "Economics",
  "Psychology",
  "Biology",
  "Chemistry",
  "Nursing",
  "Public Health",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Mathematics",
  "English",
  "Political Science",
  "Communications",
];
